### PR TITLE
Fix misplaced static()

### PR DESCRIPTION
**Pull request by mbourqui**
The `static()` method is called at the wrong place, needs to have the full page to the file or it will crash.
Learnt it the hard way...

### CODE REVIEW

**Comment by jieter** [comment]
@mbourqui Thanks for the pull. 

Can you explain in what circumstances this crash occurs and what the stack trace is?

**Comment by jieter** [comment]
Since we don't use this feature ourselves, it is critical that will get covered by a test which checks if it shows the desires behavior. It shouldn't be too hard to add such a test, are you maybe able to do that?

**Comment by mbourqui** [comment]
There are actually already some tests here: https://github.com/zostera/django-icons/blob/master/tests/test_image.py
Or would you like some more tests specific to the `get_path()` function?

**Comment by jieter** [comment]
It's always nice to have a test exposing the crash along with the fix. Can we mimic the production situation in the tests, for example by using [override_settings](https://docs.djangoproject.com/en/2.1/topics/testing/tools/#django.test.override_settings)

**Comment by mbourqui** [comment]
I will update the tests, but I need some more time.

**Comment by jieter** [comment]
Great!

**Comment by mbourqui** [comment]
Took me some time, but finally here are some more specific tests!

**Comment by dyve** [comment]
Nice! Thanks @mbourqui!

**Pull request merged**
